production:
  adapter: mysql2
  database: ests_db
  pool: 5
  timeout: 5000
  host: 162.144.210.236
  username: ests
  password: eccmadb@54321

development:
  adapter: mysql2
  database: ests_db
  pool: 5
  timeout: 5000
  host: 162.144.210.236
  username: ests
  password: eccmadb@54321

etsr_production:
  adapter: mysql2
  database: etsr_beta_new
  timeout: 5000
  host: 162.144.210.236
  # port: 3306
  username: emdv
  password: emdv123

etsr_development:
  adapter: mysql2
  database: etsr_beta_new
  timeout: 5000
  host: 162.144.210.236
  # port: 3306
  username: emdv
  password: emdv123